### ISSUE TITLE
about the Sensor data and svg.

### ISSUE THREAD

**Issue by xierunhua** [AaltoAsia/Otaniemi3D#48]
Hi, I am a student from Beijing, China . I am grad to study your code. 
And I still have 2 question, can you figure out for me ? 
Q1 :  do you have a database to storage the sensor real time data and history data ?
Q2 :  how to make the SVG file ? what kind of software do you use ?

**Comment by TK009** [comment]
Hello,
1. We use [O-MI Node](https://github.com/AaltoAsia/O-MI) as the storage which uses Open Messaging Interface as the communication standard.
2. I am not the person who made the SVG, but I think they used some CAD software to make it from the building architecture model. After that used some browser or image editor to add the identifiers for changing colors of rooms.

**Comment by MagyAndy** [comment]
thank you so much. You do a lot of work in IOT data. 
So what is the advantage of O-MI Node? I means people can use database like MSSQL,Oracle.
