### ISSUE TITLE
Hi，A Issue About Sensor

### ISSUE THREAD

**Issue by liangdwuoi** [AaltoAsia/Otaniemi3D#49]
1) what's the occupancy value meaning? how does it compute?
2) can you provide the blank of each kind of sensor? like co2, tempeture, wifi , how do the sensors send data to your platform, wireless? 4G? Narrow Band?

thank you so much.

**Comment by xierunhua** [comment]
Sorry, not blank, is brand.

**Comment by TK009** [comment]
1. If there is movement it is set to 30. After that it will decrease by one every second to zero (29, 28, 27, ..., 2, 1, 0). This helps to detect movement when data packets are lost.
2. Hardware
   * CO2, ELT sensor, S-100
   * humidity&temperature, SHT20: 
https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/0_Datasheets/Humidity/Sensirion_Humidity_Sensors_SHT20_Datasheet.pdf
   * PIR: generic sensor with BISS0001 http://www.ladyada.net/media/sensors/BISS0001.pdf
   * LUX: unknown light diode (Analog read)
   * Connection is via 6LoWPAN to a Wifi bridge that sends the packets to the server.

**Comment by xierunhua** [comment]
thank you. 
each sensor has its own Communication module ? It looks like an expensive projects.

**Comment by TK009** [comment]
They are in senor boxes which has one sensor of each kind and the communication module.

**Comment by xierunhua** [comment]
Thank you so much.
